# Generated by Django 4.2.7 on 2025-09-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='student',
            name='events_student_college_8b2c8a_idx',
        ),
        migrations.RenameIndex(
            model_name='attendance',
            new_name='events_atte_event_i_9bf8a2_idx',
            old_name='events_attend_event_i_8b2c8a_idx',
        ),
        migrations.RenameIndex(
            model_name='attendance',
            new_name='events_atte_student_2b870a_idx',
            old_name='events_attend_student_8b2c8a_idx',
        ),
        migrations.RenameIndex(
            model_name='attendance',
            new_name='events_atte_attenda_9c88c0_idx',
            old_name='events_attend_attenda_8b2c8a_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_college_51a6ba_idx',
            old_name='events_event_college_8b2c8a_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_event_t_a87b5c_idx',
            old_name='events_event_event_t_4a8b8a_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_status_5709b6_idx',
            old_name='events_event_status_8b2c8a_idx',
        ),
        migrations.RenameIndex(
            model_name='eventregistration',
            new_name='events_even_event_i_9a7faf_idx',
            old_name='events_eventr_event_i_8b2c8a_idx',
        ),
        migrations.RenameIndex(
            model_name='eventregistration',
            new_name='events_even_student_eaf200_idx',
            old_name='events_eventr_student_8b2c8a_idx',
        ),
        migrations.RenameIndex(
            model_name='eventregistration',
            new_name='events_even_status_bdf692_idx',
            old_name='events_eventr_status_8b2c8a_idx',
        ),
        migrations.RenameIndex(
            model_name='feedback',
            new_name='events_feed_event_i_a6da45_idx',
            old_name='events_feedba_event_i_8b2c8a_idx',
        ),
        migrations.RenameIndex(
            model_name='feedback',
            new_name='events_feed_student_036ab5_idx',
            old_name='events_feedba_student_8b2c8a_idx',
        ),
        migrations.RenameIndex(
            model_name='feedback',
            new_name='events_feed_rating_ec11b7_idx',
            old_name='events_feedba_rating_8b2c8a_idx',
        ),
        migrations.AddField(
            model_name='event',
            name='registration_start_date',
            field=models.DateTimeField(blank=True, help_text='When registration opens', null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, help_text='When registration closes', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
